modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/davidjjung/brushstrokes/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile = "logo.png"
itemIcon = "create:super_glue"
configBackground = "minecraft:textures/block/dirt.png"
authors="${mod_authors}"
credits = "asof"
displayURL = ""
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange="${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange="${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
mandatory = true
versionRange = "[6.0.0,)"
ordering = "AFTER"
side = "BOTH"